### PR TITLE
Adding Adam's Icelandic analyses

### PR DESCRIPTION
**Pull request by achmurzy**
Hi Aud, there are probably some organizational changes needed here. The folders that I added contain both code and data, but we can discuss how to split things up and what to include

### CODE REVIEW

**Comment by audhalbritter** [comment]
Hi Adam,
Uhh, this is exiting, I have never had a pull request! How large are these data files? I do not want to fill git with data files. We could put the data on the dropbox folder where all the other data is. But if the files are small, we could just dump them on git...

**Comment by achmurzy** [comment]
Actually Aud, it looks like your .gitignore filtered out most of it (.csv, .txt, etc). There are a couple of Rdata files in there, but all of it comes out to less than a megabyte I think. The only really hefty part is the Chelsa layers but I didn't push those. The code there assumes that they're in the folder though, which should be stated in the README as well as where to download them. I can add the sundry data files to a Dropbox following the same folder structure

**Comment by audhalbritter** [comment]
Could you write a few comments how and where to download the Chelsa data in the readme file and how what the folder structure needs to be. And if you tell me the names of the other data files I can "exclude" those in the gitignore and then merge your pull request.

**Comment by achmurzy** [comment]
Hi Aud, I added a few details on the Chelsa workflow. The data files that made it through have the extension 'RData' instead of 'Rdata'. I've always been confused about what the convention is there, exactly. Anyway you can change the .gitignore to accommodate those if you'd like. There is also iButton data called 'Celevation_TEMPfile.txt' in the 'SvalbardGradientButtonData' folder.

**Pull request merged**
